	<div class="grid">
		<h4>上传课件</h4>
			<table>
				<tr>
				<td>1.########</td><td>2010.1.1</td>
				</tr>
				<tr>
				<td>2.########</td><td>2010.1.1</td>
				</tr>
				<tr>
				<td>3.########</td><td>2010.1.1</td>
				</tr>
				<tr>
				<td>4.########</td><td>2010.1.1</td>
				</tr>
			</table>	
	</div>
	<div class="grid">
		<h4>学生作业</h4>
			<table>
				<tr>
				<td>1.########</td><td>2010.1.1</td>
				</tr>
				<tr>
				<td>2.########</td><td>2010.1.1</td>
				</tr>
				<tr>
				<td>3.########</td><td>2010.1.1</td>
				</tr>
				<tr>
				<td>4.########</td><td>2010.1.1</td>
				</tr>
			</table>	
	</div>
